---
name: CI/CD Job
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
          
      - name: Install Ruby, RubyGems, and Jekyll
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full ruby-dev build-essential
          sudo apt-get install -y rubygems
          sudo gem install jekyll bundler
          
      
      - name: Clone repository
        run: git clone git@github.com:twbs/bootstrap.git
        
      - name: Build Jekyll
        run: |
          cd bootstrap
          bundle install
          bundle exec jekyll build
      - name: Create folder
        run: |
          jekyll build
          mkdir _gh_pages
          echo "Job: ${{ job.name }} Build: ${{ env.BUILD_NUMBER }}" > _gh_pages/version.txt
          
      - name: Sync files with S3
        run: aws s3 sync . s3://Bootstrap_bucket


