---
name: CI/CD Job
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
          
      - name: Install Ruby, RubyGems, and Jekyll
        run: |
          sudo apt-get update

          sudo apt remove ruby bundler jekyll --purge
          sudo rm -rf ~/.gem ~/.ruby ~/.rvm
          sudo apt clean && sudo apt autoremove && sudo apt autoclean -y
          gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

          sudo curl -sSL https://get.rvm.io | bash -s stable --ruby
          gem install bundler jekyll
      
      - name: Clone repository
        run: git clone git@github.com:twbs/bootstrap.git
        
      - name: Build Jekyll
        run: |
          cd bootstrap
          bundle install
          bundle exec jekyll build
      - name: Create folder
        run: |
          jekyll build
          mkdir _gh_pages
          echo "Job: ${{ job.name }} Build: ${{ env.BUILD_NUMBER }}" > _gh_pages/version.txt
          
      - name: Sync files with S3
        run: aws s3 sync . s3://Bootstrap_bucket


