---
name: CI/CD Job
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Install Ruby, RubyGems, and Jekyll
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full ruby-dev build-essential
          sudo apt-get install -y rubygems
          sudo gem install jekyll bundler
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Clone repository
        run: git clone git@github.com:twbs/bootstrap.git
        
      - name: Build Jekyll
        run: |
          cd bootstrap
          bundle install
          bundle exec jekyll build
      - name: Create folder
        run: |
          jekyll build
          mkdir _gh_pages
          echo "Job: ${{ job.name }} Build: ${{ env.BUILD_NUMBER }}" > _gh_pages/version.txt
          
#       - name: Publish to S3
#         uses: s3-sync-action/s3-sync-action@v2
#         with:
#           args: --delete
#           access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           bucket_name: my-s3-bucket-name
#           local_dir: _gh_pages
